trigger: none

pool: todopool

stages:
- stage: Securityscanning
  displayName: security scanning install

  jobs:
  
    - job: 
      displayName: Biome scanning tool
      steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '18.x'
  
      - task: PowerShell@2
        continueOnError: True
        inputs:
          targetType: 'inline'
          script: |
            npm ci
            npx @biomejs/biome check .

    - job: 
      displayName: Trivy scanning tool
      steps:
      - task: PowerShell@2
        displayName: Trivy Filesystem Scan
        inputs:
            targetType: inline
            script: |
              .\trivy\trivy.exe fs . --format table
        continueOnError: true

      - task: PowerShell@2
        displayName: Trivy Dockerfile Scan
        inputs:
          targetType: inline
          script: |
            .\trivy\trivy.exe config Dockerfile --format table
        continueOnError: true
        

- stage: BuildAndPackage
  displayName: Build & Artifact Packaging

  jobs:
  -  job: 
     steps:
     - task: NodeTool@0
       inputs:
         versionSource: 'spec'
         versionSpec: '16.x'
     - task: PowerShell@2
       inputs:
         targetType: 'inline'
         script: 'npm i'

     - task: PowerShell@2
       inputs:
         targetType: 'inline'
         script: 'npm run build'

     - task: PublishPipelineArtifact@1
       inputs:
         targetPath: '$(System.DefaultWorkingDirectory)/build/'
         artifact: 'souravtodo'
         publishLocation: 'pipeline'


- stage: DeployToDev
  # condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  displayName: Deploy To Dev VM
  jobs:
  - job: deploy
    displayName: Deployement
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'souravtodo'
        targetPath: '$(System.DefaultWorkingDirectory)/build_artifacts'

    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'todoserviceconnect'
        sourceFolder: '$(System.DefaultWorkingDirectory)/build_artifacts'
        contents: '**'
        targetFolder: '/home/souravfrontendvm'
        readyTimeout: '20000'

    - task: SSH@0
      inputs:
        sshEndpoint: 'todoserviceconnect'
        runOptions: 'commands'
        commands: 'sudo cp -r /home/souravfrontendvm/* /var/www/html'
        readyTimeout: '20000'

      