trigger: none

pool: todopool

stages:

- stage: SoftwareCompositionAnalysis
  displayName: Dependency Security
  jobs: 
    - job: DepVulnScan
      displayName: Retire.js Scan
      steps: 
      - task: PowerShell@2
        displayName: Run Dependency Security Scan
        inputs:
          targetType: 'inline'
          script: |
            npm install -g retire
            npm install
            retire --exitwith 0

- stage: CodeQualityChecks
  displayName: Code Quality & Linting
  jobs:
  
  - job: BiomeLint
    displayName: JavaScript Linting (Biome)
    steps:
      - checkout: self      
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Use Node.js 18'
      - script: |
          npm ci
        displayName: 'Install dependencies'
      - script: |
          npx @biomejs/biome check .
        displayName: Biome Lint
        continueOnError: true

  - job: StylelintLint
    displayName: CSS/SCSS Linting (Stylelint)
    steps:
      - checkout: self
      - task: PowerShell@2
        continueOnError: true
        displayName: Stylelint
        inputs:
          targetType: 'inline'
          script: |
            npm install --no-save stylelint stylelint-config-standard
            npx stylelint "**/*.{css,scss}"

  - job: DotenvScan
    displayName: .env Linting (Dotenv-Linter)
    steps:
      - checkout: self

      - script: |
          npm install --save-dev dotenv-linter
        displayName: 'Install Dotenv Linter'
      - script: |
          npx dotenv-linter -- .env
        displayName: 'Run Dotenv Linter (.env)'
        continueOnError: true

  - job: Markdownlint
    displayName: .md Linting (Markdownlint)
    steps:
      - checkout: self
      - task: PowerShell@2
        continueOnError: true
        displayName: Markdown Linting (markdownlint)      
        inputs:
          targetType: 'inline'
          script: |
              npm install --save-dev markdownlint-cli   
              markdownlint $(System.DefaultWorkingDirectory)/

  - job: YAMLLint
    displayName: yaml Linting (yamllint)
    steps:
      - checkout: self
      - task: PowerShell@2
        continueOnError: true
        displayName: yamllint
        inputs:
          targetType: 'inline'
          script: |
            python -m pip install yamllint
            python -m yamllint $(System.DefaultWorkingDirectory)
        
- stage: Securityscanning
  displayName: security scanning install

  jobs:
    - job: 
      displayName: Biome scanning tool
      steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '18.x'
  
      - task: PowerShell@2
        continueOnError: True
        inputs:
          targetType: 'inline'
          script: |
            npm ci
            npx @biomejs/biome check .

- stage: TrivyScan
  displayName: Trivy Security Scan
  jobs:
    - job: Trivy
      displayName: FS + Dockerfile (Trivy Scan)
      steps:
        - checkout: self
        - task: PowerShell@2
          displayName: Install Trivy
          inputs:
            targetType: inline
            script: |
              $version = "0.68.2"
              $url = "https://github.com/aquasecurity/trivy/releases/download/v$version/trivy_${version}_windows-64bit.zip"

              Invoke-WebRequest -Uri $url -OutFile trivy.zip
              Expand-Archive trivy.zip -DestinationPath trivy -Force
              .\trivy\trivy.exe --version
        - task: PowerShell@2
          displayName: Trivy Filesystem Scan
          inputs:
            targetType: inline
            script: |
              .\trivy\trivy.exe fs . --format table
          continueOnError: true
        - task: PowerShell@2
          displayName: Trivy Dockerfile Scan
          inputs:
            targetType: inline
            script: |
              .\trivy\trivy.exe config Dockerfile --format table
          continueOnError: true

- stage: BuildAndPackage
  displayName: Build & Artifact Packaging

  jobs:
  -  job: 
     steps:
     - task: NodeTool@0
       inputs:
         versionSource: 'spec'
         versionSpec: '16.x'
     - task: PowerShell@2
       inputs:
         targetType: 'inline'
         script: 'npm i'

     - task: PowerShell@2
       inputs:
         targetType: 'inline'
         script: 'npm run build'

     - task: PublishPipelineArtifact@1
       inputs:
         targetPath: '$(System.DefaultWorkingDirectory)/build/'
         artifact: 'souravtodo'
         publishLocation: 'pipeline'


- stage: DeployToDev
  # condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  displayName: Deploy To Dev VM
  jobs:
  - job: deploy
    displayName: Deployement
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'souravtodo'
        targetPath: '$(System.DefaultWorkingDirectory)/build_artifacts'

    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'todoserviceconnect'
        sourceFolder: '$(System.DefaultWorkingDirectory)/build_artifacts'
        contents: '**'
        targetFolder: '/home/souravfrontendvm'
        readyTimeout: '20000'

    - task: SSH@0
      inputs:
        sshEndpoint: 'todoserviceconnect'
        runOptions: 'commands'
        commands: 'sudo cp -r /home/souravfrontendvm/* /var/www/html'
        readyTimeout: '20000'

      